services:

  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    container_name: nebula-backend
    hostname: nebula-backend
    restart: always

  postgres:
    image: postgres:18
    container_name: nebula-postgres
    hostname: nebula-postgres
    restart: always
    environment:
      - POSTGRES_USERNAME=ilXOMMnBGECRwyB6arz22LgfYnvZSAtvlTAmTH8q51s=
      - POSTGRES_PASSWORD=YdJQ5KhU3x1kWSq69AxCC54BTF82W1w9F1Sub+qq9Zk=
      - POSTGRES_DB=nebulaforge
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql


volumes:
  postgres-data: