spring.datasource.url=jdbc:postgresql://nebula-postgres:5432/nebulaforge
spring.datasource.username=ilXOMMnBGECRwyB6arz22LgfYnvZSAtvlTAmTH8q51s=
spring.datasource.password=YdJQ5KhU3x1kWSq69AxCC54BTF82W1w9F1Sub+qq9Zk=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect